kind: List
apiVersion: v1
metadata:
  name: registry-viewer-image-stream
  annotations:
    description: ImageStream definition for registry viewer
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: registry-viewer
  spec:
    tags:
    - name: 'latest'
      annotations:
        description: Registry Viewer image
        version: 'latest'
      from:
        kind: DockerImage
        name: registry.hub.docker.com/jiripetrlik/registry-viewer:latest
